apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '80'
spec:
  replicas: 1
  template:    
    spec:
      containers:
      - name: mongodb-exporter
        image: {{ .Values.image.repo }}:{{ .Values.image.tag }}        
        env:
        - name: MONGODB_URI 
          value: {{ .Values.mongodb.uri }}
        resources:
          limits:
            memory: "150Mi"
            cpu: "300m"                  
        ports:
        - containerPort: 80