{
 "title": "MongoDB",
 "description": "MongoDB Prometheus Exporter Dashboard.",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(mongodb_ss_connections, instance)"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "env" },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_ss_uptime" }
   ]
  },
  {
   "title": "Open Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{conn_type=\"current\"}"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "env" },
  {
   "title": "Query Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters[$interval])",
     "legendFormat": "{{legacy_op_type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_metrics_document[$interval])",
     "legendFormat": "{{doc_op_type}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "mongodb_ss_mem_resident", "legendFormat": "Resident" },
    { "expr": "mongodb_ss_mem_virtual", "legendFormat": "Virtual" }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_network_bytesOut[$interval])",
     "legendFormat": "Out"
    },
    {
     "expr": "rate(mongodb_ss_network_bytesIn[$interval])",
     "legendFormat": "In"
    }
   ]
  }
 ]
}